# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a779ab2a1e8679c0df6063260f3de64ec55de2b90fb46176027197ed553a8966c80edc562efd03ee25c6bbfca639a51733f3bd1650c136b0e4f644721bda216d

test:
  secret_key_base: f2c3ad24eaedaed738154d9e11638f0a85c3d0ef24884cb99b4ab25d27447711015f566cf60abcd98406f165565f8b1eaf02ea52bd9f1f19f054dbee2122e423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
